### ISSUE TITLE
Demo is broken (disables drag) after a search

### ISSUE THREAD

**Issue by IvanSanchez** [geoapify/leaflet-address-search-plugin#1]
Demo at https://geoapify.github.io/leaflet-address-search-plugin/ seems broken.

Steps to reproduce:
- Open webpage
- Drag the map around. Map drags as expected.
- Click on search field
- Enter name of a city
- Click on a search result. Map fits bounds as expected.
- Drag the map around. **Map dragging has been disabled** without any user notification, nor any explicit function call nor configuration setting about it.

Tested on Firefox 95 and Chromium 93 on a Debian linux box. Using trackpad (i.e. not touchscreen, not digitizer tablet). Not sure if the bug is reproducible in other platforms.

**Comment by geoapify** [comment]
> Demo at https://geoapify.github.io/leaflet-address-search-plugin/ seems broken.
> 
> Steps to reproduce:
> 
> * Open webpage
> * Drag the map around. Map drags as expected.
> * Click on search field
> * Enter name of a city
> * Click on a search result. Map fits bounds as expected.
> * Drag the map around. **Map dragging has been disabled** without any user notification, nor any explicit function call nor configuration setting about it.
> 
> Tested on Firefox 95 and Chromium 93 on a Debian linux box. Using trackpad (i.e. not touchscreen, not digitizer tablet). Not sure if the bug is reproducible in other platforms.

Nice catch! Thank you! I've found the problem and fixed it.

It should be OK now. Nevertheless, I believe there will be improvements and more plugin versions. The plugin is not a part of the Leaflet repository, so it does not affect the library itself.
